# Generated by Django 5.0.4 on 2024-04-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registrationmodel',
            table='Registration',
        ),
    ]
